public with sharing class CMRProductFind
{
  
    
    public static void findProduct()
    {
        /*
        Set<String> families = new Set<String>();
        for (CMRSales__CMRSales__c record : records) families.add(record.ProductID__c);

        Map<String, Product2> managers = new Map<String, Product2>();
        for (Product2 manager : [
            SELECT Id,Name FROM Product2
            WHERE Name IN :families
        ]) managers.put(manager.Name , manager);

        for (CMRSales__CMRSales__c  record : records)
            
            if (managers.containsKey(record.ProductID__c))
             if(record.Product__c == null){
                record.Product__c = managers.get(record.ProductID__c).Id;
            }
    }
*/
    }
}