public without sharing class PosOppMatch {
    
    
 public PageReference getsales()
    {             
       
        return null;
    }
   public PageReference updatesales(){  
      
       return null;
 }
   
    public PageReference getopps()
    {
       
        return null;
        
    }
    public PageReference updateopps(){  
       //save the opportunities after update or send error message to admin
     
       return null;
 }      


}