public class SandboxClearReseller {
    @future
    public static void clear(){
        /*
                List<Opportunity> opps = [Select Id, Partner_Account_Search__c from Opportunity where Partner_Account_Search__c != null limit 5000];
        
        for(Opportunity o: opps){
            o.Partner_Account_Search__c = null;
        }        
        database.update(opps, false);   
      */
    }

}