public class SandboxResellerAdd {
    public static void resellers(){  
        /*
        Account a = new Account();
        
        try{
            a = [Select Id from Account where Type != 'Distributor' limit 1];
                }catch(exception e){
                    a = [Select id from account limit 1];
                }
        
        List<Opportunity_Partner__c> opsinsert = new List<Opportunity_Partner__c>();
        
        List<Opportunity> opps = [Select Id,Country__c,AccountId                                  
                                  from Opportunity where SPA_Resellers__c  < 1 limit 5000];
        
        for(Opportunity o : opps){
            Opportunity_Partner__c op = new Opportunity_Partner__c(Opportunity__c = o.Id,
                                                                  Partner_Account__c = a.Id,
                                                                  Partner_Type__c = 'Reseller / VAR');
            opsinsert.add(op);
        }
        database.insert(opsinsert,false);
     */
    }

}